views:
  index: index
  about: about
  register: register
  signin: signin
  regsign: "register_signin"
  userHome: "project/list"
  adminHome: adminHome
  fragments: 
    signin: " :: signinForm"
    regsign: " :: regsignForm(active='%s')"
  errors:
    accessDenied: errors/accessDenied
    notFound: errors/notFound
    userExists: errors/userExists
  project:
    main: "project/project"
    algorithmsList: "project/algorithm/algslist"
    datasourcesList: "project/datasourcesList"
    wizardBase: "project/algorithm/wizard"
    wizard:
      datasource: "project/algorithm/wizard/datasource"
  testing:
    testindex:  testing/testindex
    hello:  testing/hello?name=Alex
    hellorest:  testing/helloREST
    hellothyme: testing/helloThyme
    welcome:  /testing/welcome
    showtable:  /testing/showtable/table/0
    listbeans: /testing/showtable/listbeans
    createalg:  /createalg